[package]
name = "practice_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
glob = "0.3.3"
petgraph = { version = "0.6", features = ["serde-1"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
